### ISSUE TITLE
Build latest prosody for EPEL7 in copr

### ISSUE THREAD

**Issue by axilleas** [librenet/ansible#39]
There are a lot of [build repos](https://copr.fedoraproject.org/coprs/fulltext/?fulltext=prosody) but none has the latest stable. I created a repo for testing https://copr.fedoraproject.org/coprs/axilleas/prosody/

**Comment by robert-scheck** [comment]
Just for the record: Latest stable version of Prosody is in EPEL 7 since 2015-05-21, see also:

 - https://apps.fedoraproject.org/packages/prosody
 - https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-5961
 - https://bodhi.fedoraproject.org/updates/?packages=prosody

Note that this was like 1.5 months before you opened this ticket ;-)

**Comment by axilleas** [comment]
Yeah, I realized that long time after I posted this issue. I can't remember why I didn't search in the repos first. Thanks for your packaging work :)
